application: pisoauction
version: 1
api_version: 1
runtime: python
threadsafe: true

handlers:

- url: /
  script: controllers/index.py

- url: /account
  script: controllers/account.py

- url: /auction/.*
  script: controllers/auction.py

- url: /checkout
  script: controllers/checkout.py

- url: /bid_packs
  script: controllers/bid_packs.py

- url: /images
  static_dir: static/images

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /user/.*
  script: controllers/testAPI.py
