application: pisoauction
version: 1
api_version: 1
runtime: python
threadsafe: true

handlers:

- url: /
  script: controllers/index.py

- url: /item/.*
  script: controllers/item.py

- url: /register
  script: controllers/register.py

- url: /validate_email
  script: controllers/validate_email.py

- url: /images
  static_dir: static/images

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /user/.*
  script: controllers/testAPI.py
