application: pisoauction
version: 1
api_version: 1
runtime: python

handlers:

- url: /
  script: home.py
  
- url: /images
  static_dir: static/images
  
- url: /css
  static_dir: static/css
  
- url: /js
  static_dir: static/js