application: pisoauction
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /test.*
  script: gaeunit.application

- url: /js
  static_dir: webclient/static/js

- url: /css
  static_dir: webclient/static/css

- url: /images
  static_dir: webclient/static/images

- url: /.*
  script: main.application



libraries:
- name: django
  version: "1.2"